import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class Inputs{
  private static JFrame frame; 
  private static JPanel myPanel; //for buttons
  private JButton button1;
  private JButton button2;

  public Inputs(){

    myPanel = new JPanel();
    button1 = new JButton("Start");
    button2 = new JButton("Quit");

    Listen ourListener = new Listen();
    //Create an action listener for two buttons to share
    button1.addActionListener(ourListener);
    button2.addActionListener(ourListener);
    myPanel.add(button1); //Add buttons to the panel
    myPanel.add(button2);
}

private class Listen implements ActionListener
{
      /**
      * Use this internal class to listen for events generated by all event sources
      * Easy to handle event code modularization
      */
      public void actionPerformed(ActionEvent e){

        String buttonName = e.getActionCommand();
        if (buttonName.equals("Start"))
        {
          JOptionPane.showMessageDialog(frame, "Starting!");
        }
        else if (buttonName.equals("Quit"))
        {
          JOptionPane.showMessageDialog(frame, "Bye mofo");
          System.exit(0);
        }
        else
        {
          JOptionPane.showMessageDialog(frame, "What did you do?");
        }
      }
}

public static void main(String s[])
{
    Inputs gui = new Inputs(); //New Simple1 component
    frame = new JFrame("Menu"); //New JFrame
    //Common methods for handling closure events
    frame.addWindowListener(new WindowAdapter() {
      public void windowClosing(WindowEvent e)
      {
        System.exit(0);
      } 
    });

    frame.getContentPane().add(myPanel);
    frame.pack(); 
    frame.setVisible(true);
}}